### ISSUE TITLE
snapshot.connectionState == waiting

### ISSUE THREAD

**Issue by eddynaka** [bizz84/firebase_auth_demo_flutter#33]
Hi,

i changed a little bit in your project to get only the mock service working. But, after that, the snapshot.connectionState is always waiting. Below some code:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: <SingleChildCloneableWidget>[
        Provider<AuthService>(
          builder: (_) => AuthServiceAdapter(),
          dispose: (_, AuthService authService) => authService.dispose(),
        ),
        Provider<EmailSecureStore>(
          builder: (_) => EmailSecureStore(),
        ),
      ],
      child: MaterialApp(
        theme: ThemeData(
          primarySwatch: Colors.indigo,
        ),
        home: LandingPage(),
      ),
    );
  }
}
```

AuthServiceAdapter.dart
```dart
class AuthServiceAdapter implements AuthService {
  AuthServiceAdapter() {
    _setup();
  }
  final JupiterAuthService _jupiterAuthService = JupiterAuthService();

  // Value notifier used to switch between [FirebaseAuthService] and [JupiterAuthService]
  ValueNotifier<AuthServiceType> authServiceTypeNotifier = ValueNotifier<AuthServiceType>(AuthServiceType.jupiter);
  AuthServiceType get authServiceType => authServiceTypeNotifier.value;
  AuthService get authService => _jupiterAuthService;

  StreamSubscription<User> _jupiterAuthSubscription;

  void _setup() {
    // Observable<User>.merge was considered here, but we need more fine grained control to ensure
    // that only events from the currently active service are processed
    _jupiterAuthSubscription = _jupiterAuthService.onAuthStateChanged.listen((User user) {
      if (authServiceType == AuthServiceType.jupiter) {
        _onAuthStateChangedController.add(user);
      }
    }, onError: (dynamic error) {
      if (authServiceType == AuthServiceType.jupiter) {
        _onAuthStateChangedController.addError(error);
      }
    });
  }
``` 

can you tell me the error?

Thanks

**Comment by eddynaka** [comment]
When I try to debug and see whats happening, for this:

```dart
 _jupiterAuthSubscription = _jupiterAuthService.onAuthStateChanged.listen((User user) {
```

it goes to a method which returns:
Unhandled exception:\nBad state: Stream has already been listened to.\n#0      _StreamController._subscribe (dart:async/stream_controller.dart:668:7)\n#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)\n#2      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)\n#3      Stream.isEmpty (dart:async/stream.dart:1015:25)\n#4      _ControllerStream.Eval ()\n#5      JupiterAuthService.onAuthStateChanged (package:jupiter/services/jupiter_auth_service.dart:18:42)\n#6      AuthServiceAdapter._setup (package:jupiter/services/auth_service_adapter.dart:25:52)\n#7      new AuthServiceAdapter (package:jupiter/services/auth_service_adapter.dart:11:5)\n#8      MyApp.build.<anonymous closure> (package:jupiter/main.dart:19:27)\n#9      BuilderStateDelegate.initDelegate (package:provider/src/delegate_widget.dart:244:14)\n#10     _DelegateWidgetState._initDelegate (package:provider/src/delegate_widget.dart:117:21)\n#11     _DelegateWidgetState.initState (package:provider/src/delegate_widget.dart:109:...

but, inside of the JupiterAuthService, i have the same as MockAuthService:
```dart
class JupiterAuthService implements AuthService {
  User _currentUser;

  final StreamController<User> _onAuthStateChangedController =
      StreamController<User>();

  @override
  **Stream<User> get onAuthStateChanged => _onAuthStateChangedController.stream**;
```
(in the bold line, i got that exception)
