### ISSUE TITLE
email_password_sign_in_page exception

### ISSUE THREAD

**Issue by joselyn9** [bizz84/firebase_auth_demo_flutter#46]
this error comes when I do a email password - signin or register
[it does log me in]
exception
 E/flutter (22129): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: No element
[        ] E/flutter (22129): #0      List.last (dart:core-patch/growable_array.dart:227:5)
[        ] E/flutter (22129): #1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:2118:43)
[        ] E/flutter (22129): #2      _EmailPasswordSignInPageState._submit
(package:firebase_auth_demo_flutter/app/sign_in/email_password/email_password_sign_in_page.dart:80:20)
[        ] E/flutter (22129): <asynchronous suspension>
[        ] E/flutter (22129): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
[        ] E/flutter (22129): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
[        ] E/flutter (22129): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] E/flutter (22129): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
[        ] E/flutter (22129): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
[        ] E/flutter (22129): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
[        ] E/flutter (22129): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
[        ] E/flutter (22129): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
[        ] E/flutter (22129): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
[        ] E/flutter (22129): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
[        ] E/flutter (22129): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
[        ] E/flutter (22129): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
[        ] E/flutter (22129): #15     _rootRunUnary (dart:async/zone.dart:1138:13)
[        ] E/flutter (22129): #16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] E/flutter (22129): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
[        ] E/flutter (22129): #18     _invoke1 (dart:ui/hooks.dart:273:10)
[        ] E/flutter (22129): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
[        ] E/flutter (22129): 

--
Thank you

**Comment by parth22** [comment]
I also face this issue when i try to login with email and password.

**Comment by bizz84** [comment]
Is this happening with the latest `master`?

**Comment by parth22** [comment]
Yes @bizz84 this is happening in this project with latest ```master``` (v0.1.2).

```
E/flutter ( 7886): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: No element
E/flutter ( 7886): #0      List.last (dart:core-patch/growable_array.dart:227:5)
E/flutter ( 7886): #1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:2118:43)
E/flutter ( 7886): #2      _EmailPasswordSignInPageState._submit (package:firebase_auth_demo_flutter/app/sign_in/email_password/email_password_sign_in_page.dart:80:20)
E/flutter ( 7886): <asynchronous suspension>
E/flutter ( 7886): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter ( 7886): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter ( 7886): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7886): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 7886): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 7886): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 7886): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter ( 7886): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 7886): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 7886): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 7886): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 7886): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 7886): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 7886): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 7886): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 7886): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 7886): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 7886): #20     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 7886): #21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 7886): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 7886): #23     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 7886): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
```

**Comment by sbadisa** [comment]
Hi, does anyone know a solution to this bug?

**Comment by sbadisa** [comment]
> Hi, does anyone know a solution to this bug?

Ok so it appears that this only happens in the emulator. When testing the app on my physical device (iphone) it does not have the bug.
